// import 'package:animated_button/animated_button.dart';
// import 'package:flutter/cupertino.dart';
// import 'package:flutter/material.dart';
// import 'package:url_launcher/url_launcher.dart';
//
// import '../botmbuton.dart';
//
// class SSec extends StatefulWidget {
//   const SSec({Key key}) : super(key: key);
//
//   @override
//   State<SSec> createState() => _SSecState();
// }
//
// class _SSecState extends State<SSec> {
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       body:  DecoratedBox(
//         decoration: BoxDecoration(
//           image: DecorationImage(image: AssetImage('assets/images/backk.jpeg'), fit: BoxFit.cover),
//         ),
//         child: ListView(
//           children: [
//             Container(
//               margin: EdgeInsets.only(top: 30,right: 40,left: 40),
//               child: Column(
//                 children: [
//                   SizedBox(height: 10),
//                   Image.asset('assets/images/topp.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/s1top.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/ss1.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss2.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss3.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss4.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss5.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss6.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss7.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss8.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss9.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss10.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss11.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss12.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss13.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss14.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss15.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss16.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss17.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss18.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/ss19.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/ss20.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss21.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss22.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss23.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss24.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss25.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss26.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss27.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss28.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss29.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss30.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss31.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss32.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss33.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss34.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss35.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss36.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss37.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss38.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss39.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss40.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss41.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss42.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss43.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss44.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss45.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss46.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss47.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss48.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss49.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss50.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss51.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss52.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss53.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss54.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss55.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss56.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss57.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss58.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss59.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss60.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss61.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss62.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss63.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss64.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss65.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss66.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss67.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss68.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss69.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss70.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss71.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss72.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss73.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss74.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss75.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss76.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss77.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss78.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss79.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss80.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss81.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss82.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss83.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss84.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss85.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss86.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss87.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss88.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss89.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss90.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss91.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss92.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss93.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss94.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss95.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/ss96.jpeg'),
//                 ],
//               ),
//             ),
//             Container(
//               child: Image.asset('assets/images/bottom.jpeg'),
//             ),
//             SizedBox(height: 20,),
//             GestureDetector(
//               onTap: ()=>
//                   _launchUrl('https://play.google.com/store/apps/details?id=appinventor.ai_seohond.elhamedia'),
//               child: Container(
//                   margin: EdgeInsets.only(left: 120),
//                   // height: MediaQuery.of(context).size.height/11,
//                   //  width: MediaQuery.of(context).size.width/9,
//                   child: Image.asset('assets/images/play.png',
//                     height: 50,
//                     width: 70,)
//               ),
//             ),
//             SizedBox(height: 10),
//             Center(
//               child: AnimatedButton(
//                 color: Color(0xffE5A726),
//                 width: MediaQuery.of(context).size.width/2.1,
//                 // shadowDegree: ShadowDegree.light,
//                 child: Text(
//                   'كل ما هو جديد',
//                   style: TextStyle(
//                     fontSize: 22,
//                     color: Color(0xff2F2D2D),
//                     fontWeight: FontWeight.w700,
//                   ),
//                 ),
//                 onPressed: () {
//                   Navigator.push(context, MaterialPageRoute(builder: (context)=>BotmBut()));
//                 },
//               ),
//             ),
//             SizedBox(height: 10),
//             Container(
//               margin: EdgeInsets.only(top: 20,left: 85),
//               child: Row(
//                 children: [
//                   GestureDetector(
//                     onTap: (){
//                       _launchUrl('https://soundcloud.com/segadet-elhamedeya/tracks');
//                     },
//                     child: Image.asset('assets/images/cloud.ico',
//                       height: MediaQuery.of(context).size.height/15,
//                     ),
//                   ),
//                   SizedBox(width: 5),
//                   GestureDetector(
//                     onTap: (){
//                       _launchUrl('https://www.youtube.com/channel/UCZRfRRy1GAJIHsCj5c-LZEA/videos');
//                     },
//                     child: Image.asset('assets/images/youtube.png',
//                       height: MediaQuery.of(context).size.height/15,
//                     ),
//                   ),
//                   SizedBox(width: 5),
//                   GestureDetector(
//                     onTap: (){
//                       _launchUrl('https://www.facebook.com/alhamdaya.alshazlaya/');
//                     },
//                     child: Image.asset('assets/images/fb.png',
//                       height: MediaQuery.of(context).size.height/15,
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//             SizedBox(height: 20,),
//           ],
//         ),
//       ),
//     );
//   }
//   _launchUrl(String url) async {
//     if (await canLaunch(url)) {
//       await launch(url);
//     } else {
//       throw 'Could not launch $url';
//     }
//   }
// }
//
