// import 'package:animated_button/animated_button.dart';
// import 'package:flutter/cupertino.dart';
// import 'package:flutter/material.dart';
// import 'package:url_launcher/url_launcher.dart';
//
// import '../botmbuton.dart';
//
// class SThird extends StatefulWidget {
//   const SThird({Key key}) : super(key: key);
//
//   @override
//   State<SThird> createState() => _SThirdState();
// }
//
// class _SThirdState extends State<SThird> {
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       body:  DecoratedBox(
//         decoration: BoxDecoration(
//           image: DecorationImage(image: AssetImage('assets/images/backk.jpeg'), fit: BoxFit.cover),
//         ),
//         child: ListView(
//           children: [
//             Container(
//               margin: EdgeInsets.only(top: 30,right: 40,left: 40),
//               child: Column(
//                 children: [
//                   SizedBox(height: 10),
//                   Image.asset('assets/images/topp.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/s1top.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/st1.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st2.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st3.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st4.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st5.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st6.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st7.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st8.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st9.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st10.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st11.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st12.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st13.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st14.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st15.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st16.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st17.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st18.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/st19.jpeg'),
//                   SizedBox(height: 30),
//                   Image.asset('assets/images/st20.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st21.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st22.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st23.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st24.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st25.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st26.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st27.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st28.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st29.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st30.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st31.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st32.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st33.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st34.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st35.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st36.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st37.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st38.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st39.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st40.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st41.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st42.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st43.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st44.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st45.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st46.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st47.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st48.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st49.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st50.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st51.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st52.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st53.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st54.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st55.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st56.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st57.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st58.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st59.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st60.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st61.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st62.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st63.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st64.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st65.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st66.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st67.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st68.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st69.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st70.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st71.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st72.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st73.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st74.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st75.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st76.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st77.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st78.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st79.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st80.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st81.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st82.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st83.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st84.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st85.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st86.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st87.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st88.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st89.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st90.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st91.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st92.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st93.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st94.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st95.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st96.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st97.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st98.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st99.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st100.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st101.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st102.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st103.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st104.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st105.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st106.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st107.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st108.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st109.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st110.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st111.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st112.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st113.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st114.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st115.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st116.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st117.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st118.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st119.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st120.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st121.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st122.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st123.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st124.jpeg'),
//                   SizedBox(height: 20),
//                   Image.asset('assets/images/st125.jpeg'),
//                 ],
//               ),
//             ),
//             Container(
//               child: Image.asset('assets/images/bottom.jpeg'),
//             ),
//             SizedBox(height: 20,),
//             GestureDetector(
//               onTap: ()=>
//                   _launchUrl('https://play.google.com/store/apps/details?id=appinventor.ai_seohond.elhamedia'),
//               child: Container(
//                   margin: EdgeInsets.only(left: 120),
//                   // height: MediaQuery.of(context).size.height/11,
//                   //  width: MediaQuery.of(context).size.width/9,
//                   child: Image.asset('assets/images/play.png',
//                     height: 50,
//                     width: 70,)
//               ),
//             ),
//             SizedBox(height: 10),
//             Center(
//               child: AnimatedButton(
//                 color: Color(0xffE5A726),
//                 width: MediaQuery.of(context).size.width/2.1,
//                 // shadowDegree: ShadowDegree.light,
//                 child: Text(
//                   'كل ما هو جديد',
//                   style: TextStyle(
//                     fontSize: 22,
//                     color: Color(0xff2F2D2D),
//                     fontWeight: FontWeight.w700,
//                   ),
//                 ),
//                 onPressed: () {
//                   Navigator.push(context, MaterialPageRoute(builder: (context)=>BotmBut()));
//                 },
//               ),
//             ),
//             SizedBox(height: 10),
//             Container(
//               margin: EdgeInsets.only(top: 20,left: 85),
//               child: Row(
//                 children: [
//                   GestureDetector(
//                     onTap: (){
//                       _launchUrl('https://soundcloud.com/segadet-elhamedeya/tracks');
//                     },
//                     child: Image.asset('assets/images/cloud.ico',
//                       height: MediaQuery.of(context).size.height/15,
//                     ),
//                   ),
//                   SizedBox(width: 5),
//                   GestureDetector(
//                     onTap: (){
//                       _launchUrl('https://www.youtube.com/channel/UCZRfRRy1GAJIHsCj5c-LZEA/videos');
//                     },
//                     child: Image.asset('assets/images/youtube.png',
//                       height: MediaQuery.of(context).size.height/15,
//                     ),
//                   ),
//                   SizedBox(width: 5),
//                   GestureDetector(
//                     onTap: (){
//                       _launchUrl('https://www.facebook.com/alhamdaya.alshazlaya/');
//                     },
//                     child: Image.asset('assets/images/fb.png',
//                       height: MediaQuery.of(context).size.height/15,
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//             SizedBox(height: 20,),
//           ],
//         ),
//       ),
//     );
//   }
//   _launchUrl(String url) async {
//     if (await canLaunch(url)) {
//       await launch(url);
//     } else {
//       throw 'Could not launch $url';
//     }
//   }
// }